# .github/workflows/android.yml
name: Build Android

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    # ---------------------------------------------------------------------
    # 1. Code
    - uses: actions/checkout@v4

    # ---------------------------------------------------------------------
    # 2. Node 16 (compatible RN 0.61-0.63)
    - uses: actions/setup-node@v4
      with:
        node-version: 16

    # ---------------------------------------------------------------------
    # 3. JDK 17 – juste pour installer le SDK
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # ---------------------------------------------------------------------
    # 4. SDK Android (action v3)
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: >-
          platform-tools
          platforms;android-32
          build-tools;33.0.2
          ndk;17.2.4988734

    # ---------------------------------------------------------------------
    # 4 bis. Purge des plateformes « ext » incompatibles avec AGP 3.x
    - name: Prune preview SDK platforms
      run: |
        echo "Avant purge :"
        ls -1 "$ANDROID_HOME/platforms" || true

        find "$ANDROID_HOME/platforms" -maxdepth 1 -type d \
             \( -name "*-ext*" -o -name "*x*" \) -print -exec rm -rf {} +

        echo "Après purge :"
        ls -1 "$ANDROID_HOME/platforms" || true

    # ---------------------------------------------------------------------
    # 5. JDK 8 – requis par Gradle 5.5 / AGP 3.x
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
        cache: gradle

    # ---------------------------------------------------------------------
    # 6. Cache npm
    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    # ---------------------------------------------------------------------
    # 7. Dépendances JS (mode tolérant)
    - name: Install JS deps (non-strict)
      run: npm install --legacy-peer-deps --no-audit --no-fund
      working-directory: telon-gateway-app

    # ---------------------------------------------------------------------
    # 8. Cache/wrapper Gradle
    - uses: gradle/actions/setup-gradle@v3

    # ---------------------------------------------------------------------
    # 9. Build APK
    - name: Assemble release
      working-directory: telon-gateway-app/android
      run: |
        chmod +x gradlew
        ./gradlew -v
        ./gradlew clean assembleRelease --no-daemon

    # ---------------------------------------------------------------------
    # 10. Artefact
    - uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: telon-gateway-app/android/app/build/outputs/apk/release/app-release.apk
