# .github/workflows/android.yml
name: Build Android

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    # 1) checkout
    - uses: actions/checkout@v4

    # 2) Node 16
    - uses: actions/setup-node@v4
      with:
        node-version: 16

    # 3) JDK 17 (uniquement pour sdkmanager)
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # 4) Installer le SDK Android (action v3)
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        components: |
          platform-tools
          platforms;android-32
          build-tools;33.0.2
          ndk;17.2.4988734

    # 4b) Auto-accept all Android SDK licenses
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    # 5) JDK 8 (pour Gradle 5.5)
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
        cache: gradle

    # 6) cache npm
    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    # 7) deps JS
    - name: Install JS deps
      run: npm install --legacy-peer-deps --no-audit --no-fund
      working-directory: telon-gateway-app

    # 7b) patch des plugins qui utilisent JavaVersion.VERSION_17
    - name: Patch JavaVersion pour plugins natifs
      run: |
        # Pour react-native-replace-dialer
        find telon-gateway-app/node_modules/react-native-replace-dialer \
          -type f -name '*.gradle' \
          -exec sed -i 's/JavaVersion\.VERSION_17/JavaVersion.toVersion(17)/g' {} +

        # Pour react-native-sip2
        find telon-gateway-app/node_modules/react-native-sip2 \
          -type f -name '*.gradle' \
          -exec sed -i 's/JavaVersion\.VERSION_17/JavaVersion.toVersion(17)/g' {} +

    # 7c) Forcer la compatibilité Java 1.8 sur tous les sous-projets
    - name: Force JavaCompile en 1.8
      run: |
        cat << 'EOF' >> telon-gateway-app/android/build.gradle
          // --- BEGIN FORCE JAVA 1.8 ---
          subprojects { project ->
            project.afterEvaluate {
              if (project.plugins.hasPlugin('java')
               || project.plugins.hasPlugin('com.android.library')
               || project.plugins.hasPlugin('com.android.application')) {
                project.tasks.withType(JavaCompile).configureEach {
                  sourceCompatibility = '1.8'
                  targetCompatibility = '1.8'
                }
              }
            }
          }
          // --- END FORCE JAVA 1.8 ---
          EOF

    # 8a) désactiver Jetifier (on est déjà en AndroidX)
    - name: Disable Jetifier
      run: |
        echo "android.useAndroidX=true" >> telon-gateway-app/android/gradle.properties
        echo "android.enableJetifier=false" >> telon-gateway-app/android/gradle.properties

    # 8) cache Gradle
    - uses: gradle/actions/setup-gradle@v3

    # 9) build APK
    - name: Assemble release
      working-directory: telon-gateway-app/android
      run: |
        chmod +x gradlew
        ./gradlew -v
        ./gradlew clean assembleRelease --no-daemon

    # 10) upload APK
    - uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: telon-gateway-app/android/app/build/outputs/apk/release/app-release.apk
