name: Android Build
on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
    # 1) code
    - uses: actions/checkout@v4

    # 2) Node (16 = encore supporté par RN 0.6x/0.7x)
    - uses: actions/setup-node@v4
      with:
        node-version: 16

    # 3) Java **8** – placé AVANT toute commande Gradle
    - uses: actions/setup-java@v4
      with:
        distribution: temurin      # ou « zulu », « adopt » …
        java-version: 8

    # 4) caches
    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    # 5) deps JS
    - run: npm ci
      working-directory: telon-gateway-app

    # 6) cache Gradle
    - uses: gradle/actions/setup-gradle@v3

    # 7) build APK
    - name: Assemble release
      working-directory: telon-gateway-app/android
      run: |
        echo "JAVA_HOME=$JAVA_HOME"      # diagnostic
        ./gradlew -v                    # vérifie que Gradle voit bien le JDK 8
        chmod +x gradlew
        ./gradlew clean assembleRelease --no-daemon

    # 8) artefact
    - uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: telon-gateway-app/android/app/build/outputs/apk/release/app-release.apk
