# .github/workflows/android.yml
name: Build Android

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with: { node-version: 16 }

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        components: |
          platform-tools
          platforms;android-32
          build-tools;33.0.2
          ndk;17.2.4988734

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
        cache: gradle

    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    - name: Install JS deps
      run: npm install --legacy-peer-deps --no-audit --no-fund
      working-directory: telon-gateway-app

    - name: Patch JavaVersion pour plugins natifs
      run: |
        find telon-gateway-app/node_modules/react-native-replace-dialer \
          -type f -name '*.gradle' \
          -exec sed -i 's/JavaVersion\.VERSION_17/JavaVersion.toVersion(17)/g' {} +
        find telon-gateway-app/node_modules/react-native-sip2 \
          -type f -name '*.gradle' \
          -exec sed -i 's/JavaVersion\.VERSION_17/JavaVersion.toVersion(17)/g' {} +

    - name: Force Java 1.8 partout
      run: |
        cat << 'PATCH' >> telon-gateway-app/android/build.gradle

        // -- FORCER COMPILATION JAVA 1.8 SUR TOUS LES SLOTS --
        subprojects {
          tasks.withType(JavaCompile).configureEach {
            sourceCompatibility = '1.8'
            targetCompatibility = '1.8'
            options.release = 8
          }
        }
        PATCH

    - name: Disable Jetifier
      run: |
        echo "android.useAndroidX=true"  >> telon-gateway-app/android/gradle.properties
        echo "android.enableJetifier=false" >> telon-gateway-app/android/gradle.properties

    - uses: gradle/actions/setup-gradle@v3

    - name: Assemble release
      working-directory: telon-gateway-app/android
      run: |
        chmod +x gradlew
        ./gradlew -v
        ./gradlew clean assembleRelease --no-daemon

    - uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: telon-gateway-app/android/app/build/outputs/apk/release/app-release.apk
