# .github/workflows/android.yml
name: Build Android

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout du code
    - uses: actions/checkout@v4

    # 2) Setup Node.js (version 16 recommandée pour React Native)
    - uses: actions/setup-node@v4
      with:
        node-version: 16

    # 3) Setup Java 8 (pour Gradle 5.x et compatibilité Android < API 24)
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
        cache: gradle

    # 4) Setup Android SDK (API 21 + build-tools compatibles Lollipop)
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        components: |
          platform-tools
          platforms;android-21
          build-tools;30.0.3
          cmdline-tools;latest

    # 4b) Accepter les licences
    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    # 4c) Créer local.properties avec le chemin vers le SDK (et NDK si utilisé)
    - name: Setup local.properties
      run: |
        mkdir -p telon-gateway-app/android
        cat <<EOF > telon-gateway-app/android/local.properties
        sdk.dir=$ANDROID_SDK_ROOT
        EOF

    # 5) Cache npm
    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    # 6) Installer les dépendances JS
    - name: Install JS deps
      run: npm install --legacy-peer-deps --no-audit --no-fund
      working-directory: telon-gateway-app

    # 7) Patch plugins natifs Java 17 => Java 1.8
    - name: Patch plugins natifs pour Java 1.8
      run: |
        for pkg in react-native-replace-dialer react-native-sip2; do
          find telon-gateway-app/node_modules/$pkg \
            -type f -name '*.gradle' \
            -exec sed -i -E \
              -e 's/JavaVersion\.VERSION_17/JavaVersion.VERSION_1_8/g' \
              -e '/\brelease\b/d' \
              -e 's/compileOptions \{[^}]*\}/compileOptions { sourceCompatibility = "1.8" targetCompatibility = "1.8" }/g' \
            {} +
        done

    # 8) Désactiver Jetifier (AndroidX déjà actif)
    - name: Disable Jetifier
      run: |
        echo "android.useAndroidX=true"  >> telon-gateway-app/android/gradle.properties
        echo "android.enableJetifier=false" >> telon-gateway-app/android/gradle.properties

    # 9) Forcer Java 1.8 dans tous les sous-projets
    - name: Force Java 1.8 partout
      run: |
        echo "
        // --- FORCE JAVA 1.8 POUR TOUS LES SOUS-PROJETS ---
        subprojects {
          tasks.withType(JavaCompile).configureEach { compileTask ->
            compileTask.sourceCompatibility = '1.8'
            compileTask.targetCompatibility = '1.8'
            try {
              compileTask.options.release = null
            } catch (MissingPropertyException _) {
              // ignore si absent
            }
          }
        }
        " >> telon-gateway-app/android/build.gradle

    # 10) Setup Gradle cache
    - uses: gradle/actions/setup-gradle@v3

    # 11) Build APK
    - name: Assemble release
      working-directory: telon-gateway-app/android
      run: |
        chmod +x gradlew
        ./gradlew clean assembleRelease --no-daemon --stacktrace

    # 12) Upload APK
    - uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: telon-gateway-app/android/app/build/outputs/apk/release/app-release.apk
