name: Android Build
on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
    # 1) Récupérer le code
    - uses: actions/checkout@v4

    # 2) Node 16 (encore compatible RN 0.71/0.72 sans bidouille OpenSSL)
    - uses: actions/setup-node@v4
      with:
        node-version: '16'

    # 3) Cache NPM
    - name: Cache NPM
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # 4) Dépendances JS
    - run: npm ci
      working-directory: telon-gateway-app

    # 5) ***Java 8*** : indispensable avec Gradle 5.x (sinon erreur Java7/Groovy)
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8

    # 6) Cache Gradle
    - uses: gradle/actions/setup-gradle@v3

    # 7) Build APK release
    - name: Assemble Release
      working-directory: telon-gateway-app/android
      run: |
        chmod +x gradlew
        ./gradlew clean assembleRelease --no-daemon

    # 8) Publier l’APK
    - uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: telon-gateway-app/android/app/build/outputs/apk/release/app-release.apk
